### ISSUE TITLE
error while making examples (add_executable)

### ISSUE THREAD

**Issue by hsab** [ofnode/of#11]
I had some issues with compiling the examples. Specifically I get an error regarding invalid number of arguments to `add_executable` in the `example()` function. Changing `add_executabl`e to:
```
add_executable(
    ${APP}
    MACOSX_BUNDLE
    ${SRC}
    ${OFXADDONS_SOURCES})
```

fixed the issue.

**Comment by avilleret** [comment]
thanks for the report
on which platform did you have the issue ?
could you please send me a pull request to fix that ?

**Comment by hsab** [comment]
I'm on Ubuntu 16.04.2 with Cmake 3.8.1.
I would submit a pull request, but my examples folder is quite different than what you have.
