### ISSUE TITLE
OSX: Files in data are not found

### ISSUE THREAD

**Issue by aspeteRakete** [ofnode/of#11]
I tried out the geometry shader example and ofShader complains:
`````
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_VERTEX_SHADER shader  from "shaders/vert.glsl"
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_FRAGMENT_SHADER shader  from "shaders/frag.glsl"
[ error ] ofShader: setupShaderFromFile(): couldn't load GL_GEOMETRY_SHADER_EXT shader  from "shaders/geom.glsl"
````
Tried to symlink shaders to bin folder and also started the binary from data folder wit ../geometryShaderExample but that didn't do the trick.
Same applies to videoPlayer.This is the first time I realize that the OF Make Sytem produces OSX *.app  binaries. Could have something to do with that.

**Comment by procedural** [comment]
That's why I needed help with OS X -- I have no idea what are you talking about :smile: What is an *.app in OS X terminology?

**Comment by procedural** [comment]
I made a page in the wiki called [Compiling ofApp with vanilla openFrameworks](https://github.com/ofnode/of/wiki/Compiling-ofApp-with-vanilla-openFrameworks), I'm sure you know already how to do that so you can try compile these examples with original repository to see how OS X applications find their data folder.

**Comment by procedural** [comment]
> Mac OS X does have the concept of "bundles" where they combine an executable and its resources into one "package" (file ending in .app)

Oh, so an *.app is a bundle of executable and data? Do you know how to put the data folder to a bundle with CMake?

**Comment by procedural** [comment]
http://www.cmake.org/cmake/help/v3.0/module/BundleUtilities.html ?

**Comment by aspeteRakete** [comment]
yeah, kind of what ubuntu snappy is about to make, afaik. I just recently got a MB, so this is all new to me too :)
Thanks for the link. I will try to implement the Bundle Functionality as soon as i got spare time.

**Comment by procedural** [comment]
@aspeteRakete sure, take your time, this project have no constraints on it! :)

**Comment by aspeteRakete** [comment]
ofnode/ofapp@99099d8b4b8f2518e9ad7601399a2afb165ec17c
enables the building of bundles.

**Comment by aspeteRakete** [comment]
i pushed that to master because of:
http://www.cmake.org/cmake/help/v3.0/prop_tgt/MACOSX_BUNDLE.html
````
When this property is set to true the executable when built on Mac OS X will be created as an application bundle.
`````
which sounds, that this has no effect, when build on other systems.

**Comment by procedural** [comment]
Cool! Does it work for you, it includes data folder to bundle?

**Comment by aspeteRakete** [comment]
Currently building ALL the examples. Will report back.... :)

**Comment by procedural** [comment]
Well, you can build only ofExamples :) Also, you can add `MACOSX_BUNDLE` to this line:

https://github.com/ofnode/of/blob/master/examples/CMakeLists.txt#L26

**Comment by aspeteRakete** [comment]
Yeah, did that and wanted to compile everything before committing.

**Comment by procedural** [comment]
@aspeteRakete thank you!
