### ISSUE TITLE
OF as submodule

### ISSUE THREAD

**Issue by aspeteRakete** [ofnode/of#12]
I just tried to use of as a submodule for an Application and modified the CMakeLists.txt as follows:
````
list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/of)
````
so of is a subfolder of the project main folder.
Trying to compile gives me a lot of errors on OSX:
````
error: gl.h included
      before glew.h
#error gl.h included before glew.h
````

**Comment by aspeteRakete** [comment]
Happens on Linux too.

**Comment by procedural** [comment]
I'll try that right now...

**Comment by procedural** [comment]
Yep, saw them too. Now I'll need to figure out why this happens...

**Comment by procedural** [comment]
o__O

```
In file included from ../src/main.cpp:1:
../of/src/glew/include/GL/glew.h:85:2: error: gl.h included before glew.h
#error gl.h included before glew.h
```

What the fuck, GLEW...

**Comment by procedural** [comment]
```cpp
#include "GL/glew.h"

int main() { return 0; }
```
```
In file included from ../src/main.cpp:1:
../of/src/glew/include/GL/glew.h:85:2: error: gl.h included before glew.h
#error gl.h included before glew.h
```
Dafuq...

**Comment by procedural** [comment]
```
#if defined(__gl_h_) || defined(__GL_H__) || defined(__X_GL_H)
#error gl.h included before glew.h
#endif
```
Some fucker defines one of these macros on a project generation step?!

**Comment by procedural** [comment]
```cpp
#include <stdio.h>

int main()
{
#if defined(__gl_h_)
printf("!!! __gl_h_ \n");
#endif
#if defined(__GL_H__)
printf("!!! __GL_H__ \n");
#endif
#if defined(__X_GL_H)
printf("!!! __X_GL_H \n");
#endif
}
```

```
$ ./ofApp
!!! __gl_h_
```

**Comment by procedural** [comment]
```bash
$ grep -FnHIr __gl_h_
of/src/glew/include/GL/glew.h:84:#if defined(__gl_h_) || defined(__GL_H__) || defined(__X_GL_H)
of/src/glew/include/GL/glew.h:103:#define __gl_h_
```
All the definitions of `__gl_h_`.

**Comment by procedural** [comment]
@aspeteRakete congrats, you found CMake's bug! :smile: No, seriously, it's their bug, we should fill it, here's a workaround for now:

```
include(of/openFrameworks.cmake)
```

Remove `list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/of)` line as well.

**Comment by procedural** [comment]
Maybe it's not CMake, maybe it's GLFW's fault, look at this:

https://github.com/ofnode/of/blob/f275776/src/glfw/deps/glad/glad.h#L9

**Comment by procedural** [comment]
I'll try to remove it, recompile OF and see if it fixes the issue

**Comment by procedural** [comment]
Aha! It's Cotire's bug, disabling it fixes the problem with appending to `CMAKE_MODULE_PATH`.

**Comment by procedural** [comment]
As a solution I'll set `include(../of/openFrameworks.cmake)` for all OF projects as the default way to find the project file for now. It's Cotire's bug, but it's too good to disable it by default and wait when it will be resolved.

**Comment by aspeteRakete** [comment]
include(of/openFrameworks.cmake)
only doesn't work on OSX.
I have to disable cotire. And when I do, it compiles and then gives a lot of linker errors, because of ofxOpenCv:
````
Undefined symbols for architecture x86_64:
  "ofxCvImage::getTexture()", referenced from:
      vtable for ofxCvColorImageAlpha in ofxCvColorImageAlpha.cpp.o
      construction vtable for ofxCvImage-in-ofxCvColorImageAlpha in ofxCvColorImageAlpha.cpp.o
`````
Could it be, that the ofxaddon() doesn't work in this setup?

**Comment by aspeteRakete** [comment]
Yes. ofxOpenCv is not build in this setup.

**Comment by procedural** [comment]
Did you have `ofxaddon(ofxOpenCv)` in your CMakeLists.txt?

**Comment by procedural** [comment]
Like so:

https://github.com/ofnode/of/blob/master/examples/CMakeLists.txt#L48

**Comment by procedural** [comment]
When yo do `ofxaddon(ofxOpenCv)` it searches for default openFrameworks addons first and if it finds, it executes its block, like this one for ofxOpenCv:

https://github.com/ofnode/of/blob/master/openFrameworks.cmake#L688-L716

**Comment by aspeteRakete** [comment]
Yes `ofxaddon(ofxOpenCv)` is in the CMakeLists.txt. 
and changing
````
list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/../of)
````
(where my standalone clone is)
to:
````
list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/libs/of)
`````
(where the submodule is)
results in the addon library not being built.

**Comment by procedural** [comment]
Do you have the same linker errors with `include(libs/of/openFrameworks.cmake)` and Cotire turned off?

**Comment by aspeteRakete** [comment]
yes

**Comment by aspeteRakete** [comment]
9818483e751c54aa8417ec7651895553978feaf5
works
but the current master doesn't. That is the problem. My standalone version was older. Must be something in the latest commits.

**Comment by procedural** [comment]
Ok, I'll make a diff and we'll see suspicious lines

**Comment by procedural** [comment]
Can you show me everything in your `CMakeLists.txt` file?

**Comment by procedural** [comment]
I think I know where the problem

**Comment by procedural** [comment]
https://github.com/ofnode/of/commit/9818483e751c54aa8417ec7651895553978feaf5 was changed from library based to source based last week. It means if the last part of the project looked like this:

```cmake
add_executable(
    ${APP}
    ${SOURCES}
)

target_link_libraries(
    ${APP}
    ${OFXADDONS_BEGIN}
    ${OFXADDONS_LIBRARIES}
    ${OFXADDONS_END}
    ${OPENFRAMEWORKS_LIBRARIES}
)
```

It should look like this now:

```cmake
add_executable(
    ${APP}
    ${SOURCES}
    ${OFXADDONS_SOURCES}
)

target_link_libraries(
    ${APP}
    ${OPENFRAMEWORKS_LIBRARIES}
)
```
Here's the commit of that change:

https://github.com/ofnode/ofApp/commit/441ff2eb71e440da9d24686e53d766c6810be6aa

Sorry, I had to notify you about it, but forgot!

The reason behind this is simple now: linkers are **unbearably** slow. Like so painfully slow on Windows and MinGW especially that I had to make ofxAddons source based. Gold linker on Linux or LLD maybe reasonably slow, but man, the one that ships with binutils is a hell.

**Comment by aspeteRakete** [comment]
alright then...

**Comment by procedural** [comment]
@aspeteRakete I hope you don't mad for this :) I promise it will be the last breaking change to ofApp. This project will be considered stable and set in stone only after the release of openFrameworks 0.9.0, -- until then we are free to introduce breakage if it lead to better features and performance

**Comment by aspeteRakete** [comment]
no, i'm not mad! :smile: 
of course you can always implement new features. 
I`m tired. have to go to bed now.  good night!

**Comment by procedural** [comment]
I've added the description of Cotire's bug to known issues: https://github.com/ofnode/of#issues

**Comment by aspeteRakete** [comment]
I have to reopen this.
changing
`````
list(APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/libs/of)
include(openFrameworks)
``````
to
````
include(libs/of/openFrameworks.cmake)
````
does not work on linux (ubuntu 14.04) and mac osx i have to comment out cotire.
When I do that it compiles and links on osx.
on Linux i get Linker errors:
````
../libs/of/lib-linux/release/libPocoUtil.a(PropertyFileConfiguration.cpp.o): In Funktion `Poco::Util::PropertyFileConfiguration::save(std::string const&) const':
PropertyFileConfiguration.cpp:(.text+0x9d1): Nicht definierter Verweis auf `Poco::OutputLineEndingConverter::OutputLineEndingConverter(std::ostream&)'
PropertyFileConfiguration.cpp:(.text+0xa07): Nicht definierter Verweis auf `Poco::OutputLineEndingConverter::~OutputLineEndingConverter()'
PropertyFileConfiguration.cpp:(.text+0xa9e): Nicht definierter Verweis auf `Poco::OutputLineEndingConverter::~OutputLineEndingConverter()'
`````

**Comment by aspeteRakete** [comment]
ahh so gold linker is mandatory?

**Comment by aspeteRakete** [comment]
doesn't work with gold.

**Comment by procedural** [comment]
Here's my repro steps:

Clone `ofApp`
Clone `of` to `ofApp/libs` folder
Replacing `include` command with `include(libs/of/openFrameworks.cmake)`
Changing directory to `ofApp/libs/of` and executing:
```bash
mkdir -p build/linux && cd build/linux && cmake ../.. -G Ninja && ninja
```
Changing directory to `ofApp` and executing:
```bash
mkdir build && cd build && cmake .. -G Ninja -DOF_ENABLE_COTIRE=OFF && ninja
```
And it compiles and links fine for me...

**Comment by procedural** [comment]
> When I do that it compiles and links on osx.
> on Linux i get Linker errors:

Ok, change directory to `ofApp/libs/of` and apply this patch with `patch -p1 < this.patch` and see if it helps:

```patch
--- a/openFrameworks.cmake
+++ b/openFrameworks.cmake
@@ -123,8 +123,9 @@
     endif()
 
     list(APPEND OPENFRAMEWORKS_LIBRARIES
+        -Wl,--start-group
         ${OPENFRAMEWORKS_LIBS}
-        ${OPENFRAMEWORKS_LIBS}
+        -Wl,--end-group
     )
 
     #// Global dependencies ////////////////////////////////////////////////////
```

**Comment by procedural** [comment]
Basically, what may happened here that for some reason I have proper link order generated by CMake and you don't... I made `OPENFRAMEWORKS_LIBS` append two times to remove expensive link groups with more "cheaper" aproach, but if it doesn't work for others I'll change it back

**Comment by aspeteRakete** [comment]
Now it links and i get:
````
../libs/of/lib-linux/release/libopenFrameworks.a(ofVideoGrabber.cpp.o):ofVideoGrabber.cpp:vtable for ofBaseVideoDraws: warning: relocation refers to discarded section
../libs/of/lib-linux/release/libopenFrameworks.a(ofVideoGrabber.cpp.o):ofVideoGrabber.cpp:vtable for ofBaseVideoDraws: warning: relocation refers to discarded section
../libs/of/lib-linux/release/libopenFrameworks.a(ofVideoPlayer.cpp.o):ofVideoPlayer.cpp:vtable for ofVideoPlayer: warning: relocation refers to discarded section
../libs/of/lib-linux/release/libopenFrameworks.a(ofVideoPlayer.cpp.o):ofVideoPlayer.cpp:vtable for ofVideoPlayer: warning: relocation refers to discarded section
`````
is this normal?

**Comment by procedural** [comment]
I found [this comment](http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20140630/224031.html):
> I think this is equivalent to bfd's famous "relocation refers to discarded section" error message.

Can you try with Gold linker and see if it produces the same warning?

**Comment by aspeteRakete** [comment]
This warning is produced by gold

**Comment by aspeteRakete** [comment]
doesn't happen with ld.bfd

**Comment by procedural** [comment]
https://sourceware.org/ml/binutils/2008-07/msg00053.html
> This can often be harmless.  For example, in some cases the compiler
will put a switch table in the .rodata section.  The switch table will
then have relocations which refer to the code.  If the code is a
template instantiation which winds up being discarded, you can get
this warning.  This is harmless because the switch table will never be
used.

**Comment by aspeteRakete** [comment]
alright then... closed for now....again! hope i don't have to reopen :dancers:

**Comment by procedural** [comment]
Templates! If I would wrote openFrameworks, not a single template would have been used :)

**Comment by procedural** [comment]
Honestly, it would have been C only. C99... :)
