### ISSUE TITLE
Arch Linux on Pi

### ISSUE THREAD

**Issue by gsautr** [ofnode/of#13]
Hi there, I'm trying to build with an Arch Linux image. 

I've updated PKG_CONFIG_LIBDIR like so, but still struggling to find all packages (freetype etc)

export PKG_CONFIG_LIBDIR=${RPI_ROOT_PATH}/usr/share:${RPI_ROOT_PATH}/usr/lib

Any pointers?

**Comment by gsautr** [comment]
-- PKG_CONFIG_PATH:
-- PKG_CONFIG_LIBDIR: /tmp/rpi/root/usr/lib:/tmp/rpi/root/usr/lib/pkgconfig/
-- PKG_CONFIG_SYSROOT_DIR: /tmp/rpi/root
-- CMAKE_FIND_ROOT_PATH : ‘/tmp/rpi/root’/opt/vc‘/tmp/rpi/root’‘/tmp/rpi/root’/usr
-- PKG_CONFIG_LIBDIR :
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY)

**Comment by avilleret** [comment]
oups I didn't see this when it was open, I hope you find a way to cross build for Raspberry Pi, if not I might help, I have an image disk ready for that under the hand
