### ISSUE TITLE
ofxaddon command

### ISSUE THREAD

**Issue by ghost** [ofnode/of#14]
In the README it is stated that one can:

`Easily add openFrameworks addons with single ofxaddon command.`

Unfortunately I cannot find the `ofxaddon` command. Is this planned for the future or did I miss something?

Very kind regards,
Hans-J.

**Comment by avilleret** [comment]
here it is : https://github.com/ofnode/of/blob/master/openFrameworks.cmake#L901

You have to include `openFrameworks.cmake` in your CMakeLists.txt, see https://github.com/ofnode/ofApp/blob/master/CMakeLists.txt#L6

but it might be buggy, feel free to report issue :-)

**Comment by ghost** [comment]
Thank you very much. And the ofxaddon command is so nice. Love it!

**Comment by avilleret** [comment]
you're welcome :-)

I tried to parse the of's `addon_config.mk` ile but it's quite hard to handle all options, so there might be some issue in weird case. If that happens to you, please report here. Thanks for your feedback
