### ISSUE TITLE
Voronoi3D won't link.

### ISSUE THREAD

**Issue by aspeteRakete** [ofnode/of#14]
`````
Linking CXX executable ../OF_GenerativeTypography/Voronoi3D/bin/Voronoi3D
duplicate symbol __ZN4voro17voro_print_vectorERNSt3__16vectorIiNS0_9allocatorIiEEEEP7__sFILE in:
    libAddons.a(common.cpp.o)
    libVoro.a(common.cc.o)
duplicate symbol __ZN4voro17voro_print_vectorERNSt3__16vectorIdNS0_9allocatorIdEEEEP7__sFILE in:
    libAddons.a(common.cpp.o)
    libVoro.a(common.cc.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

**Comment by procedural** [comment]
I'll fix it right now...

**Comment by procedural** [comment]
[I think it's fixed in latest commit, but I will make [these lines](https://github.com/ofnode/of/blob/a86b7e1/examples/CMakeLists.txt#L61-L65) for MinGW only just to be sure]

**Comment by procedural** [comment]
Or... Maybe I should add compiling addons as libraries back? Like, if it's:

```cmake
ofxaddon(addons/ofxVoro)
```

It compiles sources, but if it's:

```cmake
ofxaddon(addons/ofxVoro LIB)
```

It compiles as library to resolve duplicated symbols and links to app in the old way with this in ofApp's CMakeLists.txt:

```cmake
target_link_libraries(
    ${APP}
    ${OFXADDONS_BEGIN}
    ${OFXADDONS_LIBRARIES}
    ${OFXADDONS_END}
    ${OPENFRAMEWORKS_LIBRARIES}
)
```

?

**Comment by procedural** [comment]
I wish C++ committee would finished modules already... :)

**Comment by procedural** [comment]
Or wait... Maybe a11af40 won't fix it, I've noticed it finds the same symbol in **two different libraries** and **two different source files**, does it force us to link dynamically here? I'll comment ofxVoro library and this example for Mac for now since I don't see a fix for this retarded linker.
