### ISSUE TITLE
Build fails with debug flag

### ISSUE THREAD

**Issue by MatthewScholefield** [ofnode/of#16]
```
cmake -DCMAKE_BUILD_TYPE=Debug ..
CMake Error at of/openFrameworks.cmake:270 (message):
  No shared openFrameworks libraries found in
 project/of/lib-linux/debug-x86_64-64
  folder.
Call Stack (most recent call first):
  CMakeLists.txt:20 (include)


-- Configuring incomplete, errors occurred!
See also "project/build/CMakeFiles/CMakeOutput.log".
```
But it works fine with `-DCMAKE_BUILD_TYPE=Release` or no flag. The reason I noticed this is because it clion adds this flag by default which caused it to fail.

**Comment by avilleret** [comment]
the error message says that you don't have the core lib in debug mode
did you build of in debug mode ?

usually I made at least 4 builds of the core lib : release and debug both in static and shared mode
then I can link them easily from any other project

**Comment by MatthewScholefield** [comment]
Oh, yeah I think it was because I only ever build the library in debug more. To be honest, I didn't even realize you needed to build the library in place first before using it.

**Comment by avilleret** [comment]
> To be honest, I didn't even realize you needed to build the library in place first before using it.

this is one of the big difference between ofnode and openFrameworks build system : with vanilla build system openframeworks lib are always rebuild for each project which takes a lot of time.
With ofnode, you build all the libs once for each config then you just need to link to it
