### ISSUE TITLE
LibRawLite needs to be upgraded

### ISSUE THREAD

**Issue by MatthewScholefield** [ofnode/of#18]
With the latest sources, I get the following compilation error:
```
error: call of overloaded 'powf64(int, int)' is ambiguous
                     10*(table_buf[iLensData+9]>>2) * powf64(4, (table_buf[iLensData+9] & 0x03)-2);
```
This was fixed by upgrading to [the latest release](https://github.com/LibRaw/LibRaw/tree/0.19.0), now just called `LibRaw`, and using it to replace the `src/freeimage/Source/LibRawLite` folder.

Note: `LibRaw` is part of the provided freeimage distribution. There is an upgrade to freeimage that might solve the solution, but I ran into some other compilation errors when doing that. Would a patch that only upgrades LibRaw be of value?

**Comment by avilleret** [comment]
I know the pow64 issue, i thought I fixed it a while ago
PR are welcome btw :-)
