### ISSUE TITLE
Continuous integration and test

### ISSUE THREAD

**Issue by avilleret** [ofnode/of#20]
what about using Travis CI to automatically build `of` for several arch and running test ?
are you interested in such a thing ?

**Comment by procedural** [comment]
If it's not hard to setup, I'll add it if you want :)

**Comment by avilleret** [comment]
ho yes please :)

**Comment by procedural** [comment]
https://github.com/ofnode/of/blob/master/.travis.yml

<img src="http://www.kappit.com/img/pics/61073431bbiba_sm.jpg"/>

**Comment by procedural** [comment]
Haha, Kitware guys seems like doing straightforward approach: https://github.com/Kitware/SMTK/blob/master/.travis.yml

Will try that rather than copying it from openFrameworks...

**Comment by avilleret** [comment]
OF's travis configuration is slow because it uses sudo command to install package.
There are some tricks to use container based infrastructure that speed up the build a lot : http://docs.travis-ci.com/user/workers/container-based-infrastructure/
Build start immediately (maximum 10 second after commit).
I can have a look at that if you want.

**Comment by procedural** [comment]
@avilleret I would love too, not sure if I can find time to dig into this...

**Comment by procedural** [comment]
But, you know what... For simplicity, I think we should leave it as it is... I don't want to end up in a situation where travis is configured in one way which is different from what scripts from dev folder do.

**Comment by procedural** [comment]
And I wonder what will be the difference between `sudo: true` and `sudo: false`?

**Comment by procedural** [comment]
After 20 attempts, Linux and OS X builds are passed :) Maybe I'll add Windows later, but I'm not sure on that.

The issue is closed now!

**Comment by avilleret** [comment]
I don't know but as soon as I removed all sudo calls from my travis script,
it switched to a container based infrastructure and build time was reduced
significantly

--
do it yourself
http://antoine.villeret.free.fr

2015-09-08 13:40 GMT+02:00 Constantine <notifications@github.com>:

**Comment by procedural** [comment]
>as soon as I removed all sudo calls from my travis script

Oh, so we don't need to modify scripts from `dev` folder?

**Comment by procedural** [comment]
Because they definitely call sudo commands for installing packages and symlinking stuff..

**Comment by avilleret** [comment]
yes I know your script, and we'll need to tweak it to use container baser infrastructure.
In [other project](https://github.com/jamoma/JamomaCore) I'm not installing dependencies in Travis in the same way as one should do on its own computer.
So if this is mandatory to use exactly the same then leave it as is.
For me, since Travis is running an old system (Ubuntu 12.04) my install doesn't work, so I switched.

**Comment by procedural** [comment]
>I'm not installing dependencies in Travis in the same way as one should do on its own computer.

And this is wrong IMO. There is no point in such testing because it creates disconnect between which packages test gets and which will be installed on user machine.
