### ISSUE TITLE
Raspberry pi support

### ISSUE THREAD

**Issue by avilleret** [ofnode/of#21]
Currently of doesn't build on embedded devices.
I'm currently modifying CMakeLists.txt to build on Raspberry Pi.

**Comment by procedural** [comment]
Yea, it's because I'm focused on desktop applications. Sure, feel free to make changes and pull request, if it will work for you I'll merge it with master branch.

**Comment by avilleret** [comment]
this could be closed as soon as https://github.com/ofnode/of/pull/22 is merged :-)

**Comment by procedural** [comment]
#22 is merged! :)
