### ISSUE TITLE
doest this small warning could lead to runtime error ?

### ISSUE THREAD

**Issue by avilleret** [ofnode/of#29]
I got this warning when building on RPi2 with clang++ :

~~~~
../src/openframeworks/app/ofAppEGLWindow.cpp:181:34: warning: adding 'EGLint' (aka 'int') to a string does not append to the string [-Wstring-plus-int]
        default: str = "unknown error " + err; break;
                       ~~~~~~~~~~~~~~~~~^~~~~
../src/openframeworks/app/ofAppEGLWindow.cpp:181:34: note: use array indexing to silence this warning
        default: str = "unknown error " + err; break;
                                        ^
                       &                [    ]
~~~~

And I'm wondering if this could throw runtime error ?

**Comment by procedural** [comment]
Which runtime error you get? Can you share a backtrace from GDB?

**Comment by avilleret** [comment]
I don't get any runtime error for now and I don't know how to produce such error by intention.
I'm just wondering what this warning could cause.

**Comment by procedural** [comment]
@avilleret it won't cause runtime crash, that's for sure, most probably compiler will cast it to `char`. We can fix that warning by doing it explicitly if you want:

```cpp
default: str = "unknown error " + (char)err; break;
```

**Comment by avilleret** [comment]
ok cool if it doesn't hurt, but I'm wondering what is the output of that.
I'm not a C++ expert, but as far as I understand [string::operator+](http://www.cplusplus.com/reference/string/string/operator+=/) documentation :

~~~~
char c = 32;
string foo = "bar " + c;
cout << foo << endl;
~~~~

wouldn't output `bar 32` isn't ?

btw if this doesn't make runtime issue even with clang and since this is an OF problem, I close this ticket.

**Comment by procedural** [comment]
>wouldn't output `bar 32` isn't ?

It will output `bar 32`, indeed. Since the error is unknown in that line of OF code, I guess it simply prints its error code.

**Comment by procedural** [comment]
And, by the way, if you worry about *possible* run-time errors, I have a surprise for you: everything in modern applications can throw run time errors :D If you write production code that will be used by other people, the best you can do is to solve run time errors when they happen on their machines during beta test period.
