### ISSUE TITLE
OSX : activate retina display resolution (solved)

### ISSUE THREAD

**Issue by vrx** [ofnode/of#32]
Add in CMakeLists.txt, just before call to cotire(${APP}) 

SET_TARGET_PROPERTIES(${APP} PROPERTIES MACOSX_BUNDLE_INFO_PLIST ${CMAKE_CURRENT_BINARY_DIR}/Info.plist)

Info.plist should be copied inside "build" directory and contains
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>NSHighResolutionCapable</key>
    <true/>
  </dict>
</plist>`

**Comment by procedural** [comment]
Did you tried latest ofApp with these changes I made few weeks ago? https://github.com/ofnode/ofApp

**Comment by vrx** [comment]
Yes, It has worked for me. Though I am not sure this should be set ON by default. Default behaviour on Xcode is to set it OFF.
