### ISSUE TITLE
Gstreamer: gstconfig.h not found on Ubuntu 15.10 with gstreamer 1.6

### ISSUE THREAD

**Issue by aspeteRakete** [ofnode/of#33]
This also applies to Archlinux:
It seems the gstconfig.h has moved either with the 1.6 release or some distribution changes.
On 14.04 it is located at:
> /usr/include/gstreamer-1.0/gst/gstconfig.h

and in 15.10 at:
> /usr/lib/x86_64-linux-gnu/gstreamer-1.0/gst/gstconfig.h

So it has moved to the lib folder. Two approaches come to my mind: Fix the FindGstreamer.cmake or switch to pkgconfig. I will test if pkgconfig is feasible on both platforms.

**Comment by aspeteRakete** [comment]
pkg-config works on both systems. will assemble an PR when i got time.

**Comment by procedural** [comment]
>It seems the gstconfig.h has moved

"GNU people: moving stuff around unnecessarily since 1985."

Fixed in https://github.com/ofnode/of/commit/f226780 and checked on Ubuntu 15.10: works now.
