### ISSUE TITLE
Support for Mac OS X

### ISSUE THREAD

**Issue by osiloke** [ofnode/of#4]
Hi there,
I'm trying to compile of on osx, which compiled ok on linux, but i'm having compile errors due to missing headers. I'm not entirely sure where to add any missing includes but it seems to be due to a difference between the std lib on osx and other platforms. I posted a gist of the error log output at https://gist.github.com/osiloke/448063e7dc54ad167375. It would be nice if you could take a look at it.
Thanks

**Comment by aspeteRakete** [comment]
I am trying to get this going. My first step was to compile all the included libraries first. Except of freeglut everything compiles/links fine. Since it's deprecated i would ommit it from osx for now (glfw is the replacement everyone uses these days, right?). I'll have to poke around in the openframeworks makefiles for specific osx Definitions and find a way to include the osx frameworks. i'll report back if i run into trouble.

**Comment by procedural** [comment]
@aspeteRakete awesome! I'm surprised that you've compile all the dependent libraries given that I haven't put any thoughts on making their CMake projects compatible with OS X.

Here's idea on freeglut: let's remove it. I'm not a fan of it either, I'm maintaining patches that modify openFrameworks in this repository anyway, it's won't hurt since GLFW is a superset of things which freeglut can do.

**Comment by procedural** [comment]
OK, here's my plan for today:

 1. Remove freeglut from OF.
 2. Freeze changes on `master` probably on commit № 330 and for the next months make synchronization changes in `dev` branch.
 2. Fill up the wiki page describing the architecture of this repository, how I work with it to sync with main openFrameworks development.

**Comment by aspeteRakete** [comment]
That would be great. First issue is an issue with <tr1/memory> in ofTypes.h
When I remember tight, this has to do with libstc++. OSX ships an old version and propagates the use of libc++ (the clang version). For now i just commented out the #ifdefs, but i think this would be a job for the patch mechanism. I have never used this, so an explanation in the wiki would be great.

**Comment by aspeteRakete** [comment]
Ok, now I hang at Sound. fmod isn't in the repo for Reasons. I tried it with -DOF_SOUND_PLAYER_OPENAL, since OpenAL should provide an OpenAL implementation. Unfortunately the ofOpenALSoundPlayer.h further uses libsndfile. This can be installed with homebrew...

**Comment by procedural** [comment]
Yea, this repo doesn't contain all the libraries needed for openFrameworks, some of them are external, like these:

pkg-config
ninja
zlib
bzip2
cairo
openssl
freetype
fontconfig
opencv
openal
libusb1
libsndfile

**Comment by procedural** [comment]
You should make a script with homebrew command and place it under [dev/install](https://github.com/ofnode/of/tree/master/dev/install)/osx folder, similar to [the one from arch linux](https://github.com/ofnode/of/blob/master/dev/install/linux/archlinux.sh) for example...

**Comment by aspeteRakete** [comment]
Yep, working on it! ;) next thing is cairo...

**Comment by aspeteRakete** [comment]
Ok, next thing is this one:
```
In file included from /Users/felix/Source/of/src/openframeworks/graphics/ofImage.cpp:5:
/Users/felix/Source/of/src/freeimage/FreeImage.h:139:17: error: typedef redefinition with different types ('int32_t' (aka 'int') vs 'signed char')
typedef int32_t BOOL;
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/objc/objc.h:65:21: note: previous definition is here
typedef signed char BOOL;
                    ^
1 error generated.
```
We have different Versions of FreeImage in this repo and OF. The of Version doesn't use typedefs but #defines:
```
#ifndef _MSC_VER
// define portable types for 32-bit / 64-bit OS
#include <inttypes.h>
#define BOOL int32_t
```

**Comment by procedural** [comment]
For now just remove [these typedefs](https://github.com/ofnode/of/blob/deb0486/src/freeimage/FreeImage.h#L139-L145) if it'll work I'll patch freeimage repo

**Comment by procedural** [comment]
Oh, wait, I get it, not remove them but make them #define's

**Comment by procedural** [comment]
openFrameworks developers might face this issue too at some point, I'm using FreeImage 3.16.0 which they build with Apothecary...

**Comment by aspeteRakete** [comment]
Ok now i got a strange error compiling rtaudio:
https://gist.github.com/aspeteRakete/f475f9693981f973c6a0

**Comment by aspeteRakete** [comment]
Ok, now everything compiles. I had to do a somewhat dirty hack and put the 
> add_subdirectory(src/rtaudio)

to the top of the CMakeLists.txt, so the CXX_FLAGS isn't set when compiling rtaudio. Have to figure out a different approach.

**Comment by aspeteRakete** [comment]
Ok, it seems RTaudio wants to produce a Shared Lib for osx.
```
if(APPLE)

        add_definitions(-D__MACOSX_CORE__ -DMAC)
        add_library(rtaudio SHARED ${SRCS} ${HEADERS} )
        target_link_libraries(rtaudio)
        set_target_properties(rtaudio PROPERTIES LINK_FLAGS "-framework CoreFoundation -framework CoreAudio -framework AudioUnit -framework AudioToolbox")

    else()
```

**Comment by procedural** [comment]
Oh, yeah, fix that by making it static

**Comment by procedural** [comment]
@aspeteRakete just looked at your branch, good progress you have, keep going! Basically, as long as all examples will be compilable, I'll be happy to merge it and add you as a contributor so you could support OS X without me reviewing each PR.

**Comment by aspeteRakete** [comment]
Just tried to include GStreamer for OSX as an option. I get compile errors which i think also happened when trying to use ofxGStreamer.
````
# GStreamer Compile Errors on OSX:
/Users/felix/Source/of/src/openframeworks/video/ofGstUtils.cpp:392:6: error: no matching function for call to 'gst_element_query_duration'
        if(!gst_element_query_duration(getPipeline(),format,&durationNanos))
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/gstreamer/1.4.5/include/gstreamer-1.0/gst/gstutils.h:948:25: note: candidate function not viable: no known conversion from 'int64_t *' (aka 'long long *') to
      'gint64 *' (aka 'long *') for 3rd argument
gboolean                gst_element_query_duration      (GstElement *element, GstFormat format, gint64 *duration);
                        ^
/Users/felix/Source/of/src/openframeworks/video/ofGstUtils.cpp:578:4: error: no matching function for call to 'gst_element_query_duration'
                        gst_element_query_duration(gstPipeline,GST_FORMAT_TIME,&durationNanos);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/gstreamer/1.4.5/include/gstreamer-1.0/gst/gstutils.h:948:25: note: candidate function not viable: no known conversion from 'int64_t *' (aka 'long long *') to
      'gint64 *' (aka 'long *') for 3rd argument
gboolean                gst_element_query_duration      (GstElement *element, GstFormat format, gint64 *duration);
````
I wonder why this isn't an issue on linux? Maybe int64_t is defined as long and not long long over there?

**Comment by aspeteRakete** [comment]
also: why are you doing this:
````
if(NOT MSVC)
    target_link_libraries(
        openFrameworks
        -static-libgcc
        -static-libstdc++
    )
endif()
````
is clang ignoring the -static-* ?

**Comment by procedural** [comment]
> also: why are you doing this:
> is clang ignoring the -static-* ?

GCC and Clang both should respect these flags, I'm doing this because I had a case where I would compile OF with latest version of Clang, but when I switched to other system with older GCC it thrown it's stupid "GLIBCXX not found" error.

**Comment by procedural** [comment]
Does OS X supports GStreamer?

**Comment by procedural** [comment]
I think you should define OF_VIDEO_PLAYER_QUICKTIME instead

**Comment by procedural** [comment]
I didn't defined it for Windows or Linux because, obviously, QuickTime is closed source on Windows and it's not available on Linux at all :D I think it's closed source on OS X too (?), but that's fine since I'm sure GStreamer won't work there...

**Comment by procedural** [comment]
I see [this comment](https://github.com/openframeworks/openFrameworks/blob/31d24ea/libs/openFrameworks/utils/ofConstants.h#L311) in openFrameworks and I think it's better to use OF_VIDEO_PLAYER_AVFOUNDATION, what do you think, @aspeteRakete?

**Comment by procedural** [comment]
Maybe we should not define anything at all leaving up to openFrameworks decide what to use, depending on OS X version? I think it'll be crucial to support OS X 10.6 and 10.7

**Comment by aspeteRakete** [comment]
I already Included AVFoundation for Playback. GStreamer can be installed over homebrew (or as an Framework, see https://github.com/arturoc/ofxGStreamer/blob/master/README.md) and should work on OSX and I would like to use it. But it's not top priority right now.
I'm trying to modify openframeworks.cmake now. I obviously get a lot of linker errors right now. The -Wl,--start-group flags are not supported by OSX linker, so I fear I have to figure out the correct order. But thats something for tomorrow...

**Comment by procedural** [comment]
> The -Wl,--start-group flags are not supported by OSX linker, so I fear I have to figure out the correct order.

Here's what I have thinking lately: how's that happened that it's a year 2015, 21 century basically and we as developers don't have static link order generator still?!

I didn't knew OS X linker doesn't have groups... I always wanted to figure out the order and type it in manually without them since it affects linker performance a lot, **especially** with MinGW-w64 on Windows, oh God how slow its linker is, it took like 20 seconds for an empty ofApp...

I found [this answer on SO](https://stackoverflow.com/questions/5651869/gcc-start-group-and-end-group-command-line-options#comment6446323_5651895), maybe it will help us to figure it out.

**Comment by aspeteRakete** [comment]
![screen shot 2015-04-28 at 10 46 11](https://cloud.githubusercontent.com/assets/1003846/7366192/b7ba1bbc-ed96-11e4-921a-960cf04d98fe.png)

**Comment by procedural** [comment]
Nice! :+1: Have you figured out link order?

**Comment by procedural** [comment]
Or its linker works like in Visual Studio -- it doesn't need the order? :)

**Comment by aspeteRakete** [comment]
Seems it doesn't need it. I didn't do something special. I'm making progress on the Examples....

**Comment by aspeteRakete** [comment]
[100%] Built target xmlSettingsExample
I had to disable  osxHighPerformanceVideoPlayerExample https://github.com/openframeworks/openFrameworks/issues/3790

**Comment by procedural** [comment]
Cool! Pull request the changes!

**Comment by aspeteRakete** [comment]
Closed for now. #8
