### ISSUE TITLE
Poco Libraries

### ISSUE THREAD

**Issue by aspeteRakete** [ofnode/of#7]
I just noticed that vanilla openframeworks uses:
```
PocoCrypto.a
PocoData.a
PocoDataSQLite.a
PocoFoundation.a
PocoNet.a
PocoNetSSL.a
PocoUtil.a
PocoXML.a
PocoZip.a
```
of currently builds extra:
```
libPocoJSON.a
libPocoMongoDB.a
```
and misses:
```
PocoDataODBC.a
```
Not that I would need DB support, just wondering.

**Comment by procedural** [comment]
openFrameworks 0.8.4 used to have ODBC library, for 0.9.0 and the current master branch ODBC and MySQL are omitted, [see these comments in related Apothecary script](https://github.com/openframeworks/openFrameworks/blob/052228e/scripts/apothecary/formulas/poco/poco.sh#L17-L19). JSON and MongoDB are listed there too, I do what openFrameworks guys do to be fully compliant with their version :)
